displayName: Query Token Authentication
type: middleware
import: github.com/flohoss/token-auth
summary: Query-Token authentication middleware
testData:
  token_param: token
  cookie_name: auth_session
  allowed_tokens:
    - secret-token-1
    - secret-token-2
